
server:
  port: 9001
spring:
  application:
    name: service-sms
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/

