server:
  port: 9001

spring:
  application:
    name: service-file

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.47.150:22122


